- prepare.sh
Not every setup will have ./node_modules/.bin/ added to PATH, so reference it
relative to the project root.
---
I'm hoping that this may resolve some issues with others setting up the application. The best way to review this is to test it out by:
1. Pulling this down
1. Removing `node_modules` if you have it in place
1. Running `npm install`
1. Verifying that the installation process succeeded
@ericboucher mentioned that he was having trouble because `patch-package` wouldn't apply. I believe the reason for this is that `prepare.sh` wasn't referencing the path of the executable correctly. This should fix that. 
As a note, eventually we'd like to get rid of these patches by updating to newer versions of dependencies.
> Reference patch-package within bin folder properly

- src/shared/views/MoreOptions.js
The extra padding was cutting off the text inside the buttons. This may only be happening on iOS so a check was made specifically for that platform. It may make sense to try and move to a [React Native component library](https://blog.bitsrc.io/11-react-native-component-libraries-you-should-know-in-2018-71d2a8e33312) to get the benefits from a framework that has hopefully already solved these types of issues cross-platform visual issues.
Before:
After:
cc: @ericboucher
> fix (more-options): Fix text on more options page for iOS

- src/shared/common/ScaleBar.js
- src/shared/flow-types.js
- src/shared/views/Mapper/CardBody.js
- src/shared/views/Mapper/index.js
Scalebar added on built area projects, here's what it looks like on my phone.
It adjusts to the actual zoom level, and latitude, with preset scalebar sizes stolen from OSM
> #46 Add a scalebar to built area projects

- src/shared/views/MoreOptions.js
* and by that prevent that it overlaps with the label
below about the completed tasks
Fixes #135
> Limit nickname to one line

- src/shared/Globals.js
- src/shared/common/firebaseFunctions.js
- src/shared/constants.js
- src/shared/views/Mapper/CardBody.js
- src/shared/views/Mapper/index.js
- src/shared/views/ProjectView.js
This commit also adds support for a "completeness" project type (4).
@TahiraU have a look at the changes in here, some of them might overlap with what you are working on.
The changes here make it possible to select a specific tutorial per project:
- set a `tutorialName` key under the project in firebase with a value set to the tutorial name, such as `build_area_tutorial` to use that specific one
- if no such key exists, the app will select the default tutorial based on the project type
> #190 Setup support for custom tutorials on first project type

- docs/develop-ios.md
Fixes #236 
This updates the docs for iOS dev env setup, hopefully more in line with what is actually needed. I've removed the parts related to deployment as they are not needed to get started.
@oiva happy to get your feedback on this :)
> #236 Update iOS dev env setup docs

- src/shared/views/RecommendedCards.js
This PR brings back live updates for the project list. We used to see progress and number of mappers increase while on the list of project, but had to disable this to fix #93. Not anymore!
Fixes #119
> Live updates for project list

- src/shared/actions/index.js
- src/shared/common/ProjectLevelScreen.js
- src/shared/reducers/results.js
- src/shared/views/ChangeDetection/Body.js
- src/shared/views/Mapper/index.js
This PR removes a few `timestamp` variables that were either:
- misnamed, and I renamed them to `startTime` for more clarity
- useless, the value was passed in the action, but never actually stored, not even locally
- not wanted in firebase, this is what #227 is really about
Fixes #227
> Remove timestamp value

- ios/mapswipe.xcodeproj/project.pbxproj
Change the app's name to "MapSwipe" #196
ios/mapswipe/Info.plist seems to use $(BUNDLE_DISPLAY_NAME) variable as
_CFBundleDisplayName_ which is the name shown on users' home screen as the
app name.
The beta version bundle display name is defined in project.pbxproj
(BUNDLE_DISPLAY_NAME = "MapSwipe-beta";) but the release version did not
have BUNDLE_DISPLAY_NAME defined.
Not 100% sure if this will change the app name on iOS as I don't think I can produce production builds to test it. I did test adding the same variable for debug build and it changed the debug app's name in simulator.
> Add BUNDLE_DISPLAY_NAME for production release

- src/shared/views/Login.js
Some of the strings were listed in the translations, but not correctly picked up in the login/signup screen. This should fix the problem. It will not require further translations, as they are already listed on transifex.
> Fix some missing localization markups on the login screen

- locales/en.json
- src/shared/Main.js
- src/shared/flow-types.js
- src/shared/reducers/ui.js
- src/shared/views/MoreOptions.js
- src/shared/views/RecommendedCards.js
This PR fixes #264 by adding basic support for private projects.
If the user is part of a team, the app simply pulls private projects assigned to their team. The user can confirm if they're part of a team by checking their profile page, which shows the team name if relevant, nothing otherwise.
> #264 Add support for private projects

- package.json
- src/shared/views/Mapper/Tile.js
- yarn.lock
This PR adds support for basic http auth in imagery urls.
When creating a project, nothing changes for regular imagery sources, but if a basic auth scheme is used, the url for the imagery must be entered in the form using the standard format: `http://username:password@url` (or https if required). There is no need to use base64 or any other encoding.
React native's http client does not handle this scheme by default, instead if requires passing a `Authorization: Basic username:password` header where `username:password` is base64 encoded.
I've updated the code that grabs the url for imagery to detect if the url follows this scheme (using a regular expression) and splits the url as needed to provide the required headers. The previous logic still applies to normal urls.
> #377 Support basic http auth in imagery urls

- src/shared/common/LanguageSelectionSplashScreen.js
- src/shared/reducers/ui.js
This PR attempts to fix the crash observed upon app start with `2.0.5(0)`, which appears to be caused by the `xx` language code that was the default value expected from redux. When upgrading from the previous version, it looks like the language code was set instead to `undefined`, which was not handled in the current code, leading to the crash.
This patch should fix this, and also handle the case where the code happens to be `xx`. This should not happen, but we might as well err on the side of safety at this point!
Sorry @Hagellach37 for not seeing the problem you had pointed out in your review of the PR for `2.0.5`!
> #374 Fix crash on start due to xx language code

- .travis.yml
- android/build.gradle
- ios/mapswipe-tvOS/Info.plist
- ios/mapswipe-tvOSTests/Info.plist
- ios/mapswipe.xcodeproj/project.pbxproj
- ios/mapswipe/Info.plist
- ios/mapswipeTests/Info.plist
- ios/mapswipeUITests/Info.plist
- package.json
- yarn.lock
We are skipping 2.0.9 as there was a build/release problem with android (due to google's requirement to upgrade target sdk version to 29). Plus 2.0.9 was tagged on the wrong branch (mea culpa).
> Prepare for release 2.0.10

- src/shared/common/SatImage.js
- src/shared/views/ChangeDetection/Tile.js
This is just a tiny change to how the images are loaded for the change detection project type. (second try)
closes #492
> display imagery correctly and avoid overlay in change detection projects

- src/shared/common/ScrollableTabView/ScrollableTabView.js
The crash was due to `this` not being bound in the class method, this syntax change solves this.
The bug only happens on iOS because the code paths are quite different between platforms.
> Fix crash when swiping between tabs on ios

- android/app/src/main/AndroidManifest.xml
- docs/privacy.md
- ios/mapswipe/Info.plist
This PR tries to unlink as much personal data as possible in firebase analytics.
With these changes, if I understand the docs correctly (which is a bit of a challenge in itself), it looks like firebase analytics will not be able to link personal identifiers with activity anymore. In practice, I think this means that analytics would report something like where the user is (country-level, based on anonymised IP address), and what action they took in the app ("start mapping" for instance)
> Remove firebase tracking

- src/shared/constants.js
- src/shared/i18n.js
The translations were already merged a while back, we simply forgot to list the language as supported.
> Add support for italian translations

- .github/PULL_REQUEST_TEMPLATE/new_release.md
Closes #546 
This PR adds a template for PRs that prepare a production release, with a checklist meant to avoid forgetting the basics.
Feel free to add links to documentation or less code-related items.
> Add pre-release PR template

- src/shared/constants.js
- src/shared/i18n.js
The translation PR from transifex is already merged, this just declares the language so it's available in the language selection menu.
> Add support for Esperanto

- src/shared/actions/index.js
- src/shared/common/AccessibilityInfoModal.js
- https://github.com/mapswipe/mapswipe/issues/873
- https://github.com/mapswipe/mapswipe/issues/882
- Fix accessibility modal instructions
- Add system name on mapping (eg: `clientType: android`)
- Fix accessibility modal instructions
> Add device type on mapping

- patches/react-native+0.72.5.patch
- Reference: https://github.com/facebook/react-native/issues/33462#issuecomment-2608624733
> Fix failing pod install because of boost binary hosted in jfrog.io
