mapswipe/mapswipe

.gitignore
ios/Mapswipe.xcodeproj/project.pbxproj
ios/Mapswipe/Info.plist
src/shared/views/Login.js
src/shared/views/ProjectNav.js
src/shared/views/Tutorial.js

First attempt to update Firebase events, here are the changes:
- Add account_screen_seen when loading Login
- Add account_creation_error_username and account_creation_error_db for errors
- Remove misleading starting_tutorial
- Move starting_tutorial to the render section
- Add completed_tutorial

Update Firebase user events

---

src/shared/Database.js
src/shared/Globals.js
src/shared/actions/index.js
src/shared/flow-types.js
src/shared/reducers/results.js
src/shared/views/BuildingFootprint/FootprintDisplay.js
src/shared/views/BuildingFootprint/Validator.js
src/shared/views/BuildingFootprint/index.js
src/shared/views/LoadMore.js
src/shared/views/Mapper/CardBody.js
src/shared/views/Mapper/IndividualCard.js
src/shared/views/Mapper/Tile.js
src/shared/views/Mapper/index.js
src/shared/views/ProjectCard.js
src/shared/views/ProjectView.js
src/shared/views/RecommendedCards.js

This fixes #47 in relation to the changes in the backend's data structure.

New backend structure

---

.gitignore
.travis.yml
ios/Podfile.lock
ios/cfg/debug.xcconfig
ios/cfg/prod.xcconfig
ios/fastlane/Fastfile
ios/fastlane/Matchfile
ios/fastlane/README.md
ios/mapswipe.xcodeproj/project.pbxproj
ios/mapswipe/Info.plist

- Added a lane in fastlane to update the development certificates with the correct bundle ID.
- Changed the team in fastlane config
- Changed the team in the targets settings
- added some files in gitignore already present on disk.

Org change

---

ios/mapswipe-tvOS/Info.plist
ios/mapswipe-tvOSTests/Info.plist
ios/mapswipe.xcodeproj/project.pbxproj
ios/mapswipe/Info.plist
ios/mapswipeTests/Info.plist
ios/mapswipeUITests/Info.plist
package.json
src/shared/views/Mapper/IndividualCard.js

Fixes #147, based on feedback from users outside of github

Fix tapping issues

---

android/app/build.gradle
android/app/src/main/java/org/missingmaps/mapswipe/MainApplication.java
android/settings.gradle
ios/Podfile
ios/mapswipe-tvOS/Info.plist
ios/mapswipe-tvOSTests/Info.plist
ios/mapswipe.xcodeproj/project.pbxproj
ios/mapswipe/Info.plist
ios/mapswipeTests/Info.plist
ios/mapswipeUITests/Info.plist
package.json
src/shared/constants.js
src/shared/views/ChangeDetection/ChangeDetector.js
yarn.lock

Update the Change Detection layout to match @jhenshall 's design proposal

Cd gradient

---

src/shared/common/tile_functions.js

Fixes #246 
@Hagellach37 I've figured this out by trial and error, but please check that it actually makes sense with the way the backend creates projects, and overall TMS definitions.

#246 Fix broken custom TMS imagery url calculation

---

ios/mapswipe-tvOS/Info.plist
ios/mapswipe-tvOSTests/Info.plist
ios/mapswipe.xcodeproj/project.pbxproj
ios/mapswipe/Info.plist
ios/mapswipeTests/Info.plist
ios/mapswipeUITests/Info.plist
package.json
src/shared/views/Mapper/IndividualCard.js

This fixes #240 that was reported by a user earlier today.
WIP: do not merge until test confirmed by user!

Prevent tiles from displaying on 4 rows

---

locales/en.json
src/shared/views/LoadMore.js

Rebased change from #255 to the now quite recent dev-branch.

Beautify sync alert

---

locales/en.json
src/shared/views/ProjectNav.js

I strongly believe those should be lower case :)

Small en json change

---

ios/mapswipe-tvOS/Info.plist
ios/mapswipe-tvOSTests/Info.plist
ios/mapswipe.xcodeproj/project.pbxproj
ios/mapswipe/Info.plist
ios/mapswipeTests/Info.plist
ios/mapswipeUITests/Info.plist
package.json
src/shared/actions/index.js
src/shared/common/Tutorial/TutorialEndScreen.js
src/shared/flow-types.js
src/shared/reducers/ui.js
src/shared/views/ProjectView.js

This PR forces users of a private project through the corresponding tutorial if they've never completed it before.
This behaviour should probably be extended to all users, but we need to translate the entire tutorial before doing so.

Force first time tutorial

---

ios/mapswipe.xcodeproj/project.pbxproj
ios/mapswipe/Info.plist
ios/mapswipeTests/Info.plist
ios/mapswipeUITests/Info.plist
package.json
src/shared/views/ChangeDetection/Body.js
src/shared/views/Mapper/index.js
src/shared/views/ProjectView.js

@laurentS can you check if this is enough?

fix import of Modal component

---

ios/mapswipe.xcodeproj/project.pbxproj
ios/mapswipe/Info.plist
ios/mapswipeTests/Info.plist
ios/mapswipeUITests/Info.plist
package.json
patches/@react-native-firebase+app+12.3.0.patch

This is just a hotfix patch that corrects [this bug](https://github.com/invertase/react-native-firebase/issues/5544) in RNFirebase. The patch can be removed once the dependency has issued a fix.

Fix rnfb listeners bug

---

src/shared/views/LoadMore.js

This is a proposal for how we could check for additional task and alert sentry. 
The question we asked ourselves was, how we would test if it works if we can not reproduce the issue.
Addresses:
- #619

Draft: Alert wrong tasks no

---

yarn.lock

fix a number of security notices

Upgrade js dependencies

---

android/app/src/main/AndroidManifest.xml
android/build.gradle

Hopefully this will be enough to be able to release a new version.

Upgrade to targetSdkVersion 31 to pass playstore requirements

---

src/shared/common/CalendarHeatmap.js
src/shared/constants.js
src/shared/views/UserGroup.js

Address
- https://github.com/mapswipe/mapswipe/issues/765
- https://github.com/mapswipe/mapswipe/issues/764
Changes
- Share algorithm used to create linechart in community dashboard to populate data for calendar heatmap
- Use custom Button in UserGroup component

Fix problem with calendar heatmap

---

.github/workflows/ios.yml
locales/en.json

- https://github.com/mapswipe/mapswipe/issues/813
- https://github.com/mapswipe/mapswipe/issues/814
- Fix static text message

Fix minor text message

---

locales/en.json
src/shared/common/SatImage.js
src/shared/views/ChangeDetection/Body.js
src/shared/views/ChangeDetection/Task.js
src/shared/views/ChangeDetection/TaskList.js
src/shared/views/ChangeDetection/Tile.js
src/shared/views/Mapper/CardBody.js
src/shared/views/Mapper/IndividualCard.js
src/shared/views/Mapper/Tile.js
src/shared/views/UserProfile.js

- Add feature to on/off accessibility 
- Implement on project mapping

Feature/accessibility UI on/off

---

src/shared/common/AccessibilityInfoModal.js
src/shared/views/ChangeDetection/Body.js
src/shared/views/ChangeDetection/InstructionsScreen.js
src/shared/views/Mapper/CardBody.js
src/shared/views/UserProfile.js

- Accessibility feature fix
- Change tap to hide icon on mapping info
- Fix overflow modal
- Clear async storage after logout

Improve accessibility feature UI

---

ios/mapswipe.xcodeproj/project.pbxproj
ios/mapswipe/Info.plist
ios/mapswipeTests/Info.plist
ios/mapswipeUITests/Info.plist
locales/en.json
package.json
src/shared/common/Button.js
src/shared/utils.js
src/shared/views/ChangeUserName.js
src/shared/views/Login.js

- Improve validation condition for username creation
- Add same validation on change username from profile section
- Now username cannot contain space and capital letter (New feature)
- Username cannot contain `@` also existing behavoir

Improve condition for username creation

---

.github/workflows/android.yml
.github/workflows/build.yml
.github/workflows/ios.yml

Update following packages
- actions/checkout@v1 -> v4
- actions/setup-node@v1 -> v4
- actions/upload-artifact@v2 -> v4
- softprops/action-gh-releases@v1 -> v2

Update github workflow packages

---

changelog.json
src/shared/common/AccessibilityInfoModal.js
src/shared/common/ChangelogModal.js
src/shared/constants.js
src/shared/views/ProjectNav.js

- https://github.com/mapswipe/mapswipe/issues/863
Note: Going forward, we also need to add changelogs to `changelog.json` file! CC: @kopitek8

Add changelog popup

---

changelog.json
locales/en.json
src/shared/flow-types.js
src/shared/views/BuildingFootprint/Validator.js

- https://github.com/mapswipe/mapswipe/issues/815

Fix advancement logic for validate tutorial
